# Generated by Django 4.2.7 on 2025-12-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_review',
            field=models.BooleanField(default=True, help_text='Allow students to review answers'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, help_text='When quiz closes', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='When quiz becomes available', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_score',
            field=models.BooleanField(default=True, help_text='Show score to students'),
        ),
    ]
